# Generated by Django 4.2.1 on 2023-12-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='faculty/images/')),
                ('position', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('bio', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=200)),
                ('prof_exp', models.CharField(max_length=150)),
                ('projects', models.CharField(max_length=200)),
                ('linkedIn', models.URLField()),
                ('facebook', models.URLField()),
                ('x', models.URLField()),
                ('irins', models.URLField()),
            ],
        ),
    ]
