# Generated by Django 4.2.1 on 2023-12-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='id',
        ),
        migrations.AddField(
            model_name='faculty',
            name='No',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
