# Generated by Django 4.2.1 on 2023-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_faculty_id_faculty_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
