# Generated by Django 4.2.1 on 2024-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_faculty_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='No',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
