# Generated by Django 4.2.1 on 2024-01-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_alter_faculty_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='facebook',
            new_name='officiallink',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='irins',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='linkedIn',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='prof_exp',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='x',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='No',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
