# Generated by Django 4.2.1 on 2024-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_facebook_faculty_officiallink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
