# Generated by Django 4.2.1 on 2024-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Domains', '0003_deleteditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteditem',
            name='name',
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Announcement1',
            field=models.TextField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Announcement2',
            field=models.TextField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Announcement3',
            field=models.TextField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_3',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_4',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_text_1',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_text_2',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_text_3',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deleteditem',
            name='Link_text_4',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
