# Generated by Django 4.2.1 on 2024-01-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Title', models.CharField(max_length=50)),
                ('Enter_Announcement', models.CharField(max_length=100)),
            ],
        ),
    ]
